services:
  backend:
    build:
      context: .
      dockerfile: SistemaAPI/Dockerfile
    ports:
      - "5198:5198"
    volumes:
      - ./SistemaAPI:/SistemaAPI # Montando o diretório local da API
      - ./SistemaAPI/Users.db:/app/Users.db # Persistindo o banco de dados SQLite
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network
    volumes:
      - ./frontend:/app

networks:
  app_network:
    driver: bridge
